### ISSUE TITLE
Named anchors and "current section" not working as expected

### ISSUE THREAD

**Issue by PavelSafronov** [dolthub/docs#1512]
1. maximize your browser
2. Navigate to https://docs.dolthub.com/sql-reference/version-control/dolt-system-tables#dolt_schema_conflicts.
3. The table we're interested in is `dolt_schema_conflicts`, and this is what should be shown in the main column
4. On the right-hand side, note that `dolt_merge_status` is highlighted as being the "current" topic

![image](https://github.com/dolthub/docs/assets/1359724/358332d2-cc39-47d7-831d-e0636b8126c5)

**Comment by tbantle22** [comment]
Looks like this has been fixed
