### ISSUE TITLE
blog: "Writing and debugging integration tests of multiple processes with Golang" contains error

### ISSUE THREAD

**Issue by marco-m** [dolthub/docs#1589]
Hello,

thanks for your Go blog! (and also for dolt, although I didn't have the occasion yet to use it).

I had a quick look but could not find the blog source on github/dolthub, so I am opening this issue here.

The blog post https://www.dolthub.com/blog/2023-05-25-debugging-multiple-golang-processes/ contains an example code with an error:

```go
func (s *SqlServer) GracefulStop() error {
	s.Cmd.Process.Kill()                           // <= HERE
	err := s.Cmd.Process.Signal(syscall.SIGTERM)
	if err != nil {
		return err
	}
	<-s.Done
	return s.Cmd.Wait()
}
```

`s.Cmd.Process.Kill()` is not graceful, so it should be sent after SIGTERM (and a timeout) or should not be sent at all.

Looking in the dolt code, I found https://github.com/dolthub/dolt/blob/main/go/libraries/doltcore/dtestutils/sql_server_driver/cmd_unix.go#L29, so it seems it is already fixed there. What it missing is to remove the line from the blog article.

**Comment by fulghum** [comment]
Hey @marco-m, thanks for reading our Golang blogs and taking the time to report an issue in the sample code. 

@zachmu – you wanna take a look at this one and pull that line from the sample?

**Comment by zachmu** [comment]
Good catch! I'll go ahead and remove that from the blog today.
