### ISSUE TITLE
New Doc: Importing Data guide

### ISSUE THREAD

**Issue by timsehn** [dolthub/docs#436]
We should have a detailed document on how to get data into Dolt from the following sources:

1. MySQL 
2. Postgres
3. CSVs

**Comment by timsehn** [comment]
Have X, Want Dolt.

X can be:

1. MySQL
2. Postgres
3. CSVs
4. Spreadsheets
5. Pandas
6. Other databases (SQL Server, Oracle DB 2)

**Comment by VinaiRachakonda** [comment]
Cool, thanks for the note. This will be in ASAP

**Comment by timsehn** [comment]
May also want to cover this here:

https://github.com/dolthub/docs/issues/542

**Comment by timsehn** [comment]
Resolved by @VinaiRachakonda
