### ISSUE TITLE
Add "Why do inserts get slower as my database gets larger?" FAQ Item

### ISSUE THREAD

**Issue by timsehn** [dolthub/docs#542]
This behavior confuses people.

There are two possible reasons:

1. Depth of tree (small)
2. Mega chunks (large)

We need to explain this.

**Comment by zachmu** [comment]
Going to benchmark this to be sure before I write about it.

But the intuition is: importing in sorted order will help a lot.

**Comment by VinaiRachakonda** [comment]
@zachmu Do you still want to write about or should I start by adding a basic note in #719
