### ISSUE TITLE
CLI reference doesn't list all `dolt` subcommands

### ISSUE THREAD

**Issue by bl-ue** [dolthub/docs#58]
I'm writing [tldr](https://github.com/tldr-pages/tldr) pages for all of the `dolt` commands, and when we write tldr pages we like to like to the home page/man page of the specific command we're documenting, so that users can learn more about the command from official sources of documentation.

Each subcommand gets its own page and therefore gets its own link.  I'd like to link to the subcommand's entry on https://docs.dolthub.com/interfaces/cli, e.g. `dolt add` would have https://docs.dolthub.com/interfaces/cli#dolt-add as a link, but I can't do that very easily because only 21 of the total 32 subcommands are listed there.

Currently, the only `dolt` subcommands missing from https://docs.dolthub.com/interfaces/cli are:
- `conflicts`
- `creds`
- `filter-branch`
- `gc`
- `migrate`
- `read-tables`
- `schema`
- `table`
- `tag`
- `verify-constraints`
- `version`

The commands themselves have `--help` options which display help information, so it looks like a simple copy and paste from there to the docs page would do the trick.  Is it not that simple?

**Comment by timsehn** [comment]
Transferring to the docs repo.

**Comment by bl-ue** [comment]
Is have any system to sync the CLI help with the docs page?  I'm noticing some inconsistencies.

Also, [this change](https://github.com/dolthub/docs/commit/b99b08cd3dfb955945899bc72ccbe78ff8e6e106) hasn't been [deployed](https://docs.dolthub.com/interfaces/cli#description-13) yet.

**Comment by timsehn** [comment]
Yes. @Oscar Batori ***@***.***> built a program to do it. We just
need to run it manually.

**Comment by oscarbatori** [comment]
Correct, thanks for this @timsehn.

@bl-ue hopefully we can get this out in the next few days.

**Comment by bl-ue** [comment]
So is it safe for me to link to, for example, https://docs.dolthub.com/interfaces/cli#dolt-filter-branch, though that page doesn't exist yet?

**Comment by oscarbatori** [comment]
@bl-ue the link you are referencing now works as expected.

**Comment by bl-ue** [comment]
Thank you!

I noticed one thing, https://docs.dolthub.com/interfaces/cli#description-2, it's still using the broken link https://en.wikipedia.org/wiki/File_URI_schemethi (which the CLI has too) 🤔

**Comment by oscarbatori** [comment]
@bl-ue it appears we didn't merge a typo fix for that, will do so today. Thanks for pointing that out.
