### ISSUE TITLE
New Doc: SQL Reference/Version Control Features/Merge

### ISSUE THREAD

**Issue by timsehn** [dolthub/docs#632]
1. How conflicts are calculated
    1. data
    1. schema
1. The `dolt_conflicts` and `dolt_conflicts_<tablename>` tables
    * Schema conflicts are not resolvable via SQL
3. Resolving conflicts in SQL 
    * Note must resolve in a single transaction
1. Persisting conflicts to resolve later (not default)

**Comment by timsehn** [comment]
Conflict detection logic is specced here:

https://docs.dolthub.com/concepts/dolt/conflicts

Could be improved

**Comment by druvv** [comment]
Will come back to this after June 15th. Going to move forward on the suggestion to create a doc about merge in general in the SQL context.

**Comment by timsehn** [comment]
New idea is to take all the content after:

https://docs.dolthub.com/sql-reference/version-control/branches#merging-branches

And rewrite it talking about AUTOCOMMIT off for merge. This has most of the content we want but can be combined with the ideas above to make a great doc we're proud of.
